# Generated by Django 5.0.5 on 2024-12-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0005_diagnosis_patient1_delete_patient_diagnosis_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient1',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='patient1',
            name='diagnosis_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='patient1',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
