# Generated by Django 5.0.5 on 2024-12-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0008_remove_notification_doctor_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='symptoms',
            field=models.TextField(default=''),
        ),
    ]
