# Generated by Django 5.0.5 on 2025-02-04 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0010_signup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='role',
        ),
    ]
