# Generated by Django 5.0.5 on 2025-02-04 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0013_register1_delete_register'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register1',
            new_name='Register',
        ),
    ]
